### ISSUE TITLE
Come up with a new slogan at right of the header

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#10]
(via Craig)

**Comment by equivalentideas** [comment]
The current slogan is:

> Making government work better for people through transparency, participation and accountability

![screen shot 2016-01-19 at 3 55 06 pm](https://cloud.githubusercontent.com/assets/1239550/12410075/560f3360-bec5-11e5-8418-59bcb46a97c2.png)

Which comes straight from the UK version.

What’s the reason we'd want to change this?

**Comment by henare** [comment]
> What’s the reason we'd want to change this?

I say we leave it as is for the moment or until we can answer that question. It might change as a result of #12 as well.
