### ISSUE TITLE
Direct people to join the network before they join the Google Group

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#101]
(via Peter Timmins) user feedback from Peter - currently there are two paths to getting involved - get involved page points to joining the network with the agreement to be aligned with civil society interests, and diving into working groups which currently doesn't require this. We're trusting people to commit to the network principles and ask that they do so to contribute to the working group conversations.

**Comment by kat** [comment]
There's no membership form to join through the google group - a quick fix in the short term can be  to request "if you want to take part in the conversation here join the network" first: -and link to form -  https://groups.google.com/forum/#!forum/aogpn 

I suggested that topic facilitators being responsible that those taking part in conversation can help by checking participants joining their group have signed up to the network. 

Although Peter raised that current members of this group have not filled in the form, they are the current steering committee and have thus agreed to the terms.

**Comment by kat** [comment]
@craigthomler can you please add "To participate in this group, please [join the network](https://docs.google.com/forms/d/1Rwq8cLkSUQBRVin33QmMc2xwsgeA91DP_i5u3dLYIoA/viewform)"  in the [google group introductory text](https://groups.google.com/forum/#!forum/aogpn)

**Comment by kat** [comment]
@equivalentideas - please can you pick this one up? ( please add "To participate in this group, please join the network" in the google group introductory text as above)

**Comment by equivalentideas** [comment]
Done:
![screen shot 2016-02-09 at 10 56 55 am](https://cloud.githubusercontent.com/assets/1239550/12903477/efb8c984-cf1b-11e5-997b-2b51b370b4f1.png)

@kat should we put notices like this on the working group pages? We are currently pushing people to working group pages that link directly to their threads in the google group, bypassing the welcome message.

**Comment by equivalentideas** [comment]
> @kat should we put notices like this on the working group pages? We are currently pushing people to working group pages that link directly to their threads in the google group, bypassing the welcome message.

@henare suggested that we want to add notices/links like the :point_up: to all the working group pages above the links to the google group.

I'm gonna do that, and change the name of this issue, and we can go from there.

**Comment by equivalentideas** [comment]
Ok, I've added that notice to the top of all the working group pages and to the [Working Groups page](https://opengovernment.org.au/working-groups/).

Closing this.
