### ISSUE TITLE
add new email and twitter information

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#103]
add @opengovau and opengovau@gmail.com to the contact/social information (Peter Timmins organising these)

**Comment by henare** [comment]
> ...and opengovau@gmail.com...

What about #82?

**Comment by kat** [comment]
Peter is the contact for the network and takes responsibility for this email address.

**Comment by henare** [comment]
:+1:

**Comment by henare** [comment]
Done.
