### ISSUE TITLE
Describe Anticorruption working group

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#114]
https://opengovernment.org.au/working-groups/anti-corruption/

From Peter for the interim until we get something from Phil or others:

Anti Corruption

There are critical deficiencies in Australia’s anti-corruption laws and policy framework,

Australia has fallen further on the international Corruption Perceptions Index (CPI) published by Transparency International for the third year in a row.
http://transparency.org.au/index.php/media-release/australias-international-corruption-reputation-continues-to-tumble/

World-wide perceptions of the level of corruption in Australia’s government sector continue to worsen, with Australia’s CPI score falling to 79, down from 85 in 2012, 81 in 2013 and 80 in 2014.

Australia is now ranked 13th out of the 168 countries included in the Index – down six positions since 2012.

Position Papers published by Transparency International Australia highlight the scope for reforms that would start to address this decline and the low level of trust in government and government institutions

http://transparency.org.au/index.php/current-news/release-of-position-papers-on-key-issues/

Issues raised include

 The adequacy of Australia’s institutional arrangements for fighting corruption:

```
variable, inconsistent or missing legal definitions of official corruption;
whether ACA’s efforts are properly prioritised, proactive and coordinated with other agencies;
insufficient confidence that action is being taken to deal properly with individuals who engage in or benefit from corrupt conduct that is uncovered;
whether ACAs have the right powers, sufficient resources and necessary independence from government;
adequacy of accountability, oversight and performance assurance arrangements; and
gaps in arrangements at the Australian federal government level…
```

Public Procurement arrangements.

Political Finance, Donations and Lobbying: "disclosure of political donations is not timely, with delays in publication of party funding of up to 19 months after elections.  This means that electors cannot exercise their vote in an informed way and there are increased possibilities of skewing democracy with secret donations and vote buying.  It is of little use to the democratic process if the law allows donations to be declared many months after an election.The risks of corruption are heightened by inconsistencies in Commonwealth and State legislation relating to electoral finance, disclosure and lobbying…"

Whistleblowing: "While Australia has been at the forefront of recognising the role of whistleblowing in its public integrity systems, there remain major problems:

```
Nationally, legal protections for business and civil society whistleblowers are largely missing
At federal and state level, key government whistleblower protection legislation remains incomplete or out-of-date
The effectiveness of existing legislation in delivering remedies for employees who suffer detriment as a result of making a public interest disclosure remains highly uncertain
Not enough is known about best practice approaches to facilitating and protecting whistleblowing within organisations (especially in the private sector); and
There is a lack of independent advice and support services for employees who are considering, or who do, blow the whistle on wrongdoing…"
```

**Comment by henare** [comment]
Done: https://opengovernment.org.au/working-groups/anti-corruption/
