### ISSUE TITLE
do we need a sign up for businesses - distinguish them from non-profit organisations

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#117]
Business people have signed up giving a business name where asked for an organisation name. Is that appropriate?

**Comment by kat** [comment]
should we offer the option to chose 'business' rather than organisation, as we're not against business people, and we do want to understand people's motivations for joining.

**Comment by equivalentideas** [comment]
> should we offer the option to chose 'business' rather than organisation, as we're not against business people, and we do want to understand people's motivations for joining.

@kat I'm not sure at this stage. It's not clear to me what the actual problem/bug is that this issue is identifying. Could you have a go articulating this from the perspective of what we're missing out on at the moment and why it's a problem?

**Comment by kat** [comment]
It's good for transparency. AOGPN is an civil society network. The intention originally for the organisation field in the form was that if people signed up on behalf of an organisation it was presumed to be a civil society organisation (CSO). However two business people have put for profit businesses into this field as their organisation. This is misleading as they're not a civil society organisation.

Offering a business option is a way for them to state who they represent (a business) without misleading anyone into thinking they represent a civil society organisation (CSO).

**Comment by equivalentideas** [comment]
> AOGPN is an civil society network.

It seems odd to have businesses sign up at all. As you say above “we're not against business people”, and they can join as individuals.

Would another solution be to make it clearer that you're signing up a civil society organisation, rather than any kind of organisation. I think it could be unclear at the moment to people that their business/org is becoming a member as we use the words “representative of an organisation”.

So change the current question:

> If you are joining as a representative of an organisation, what’s its name?

to:

> If you are registering a civil society organisation as a member, what’s its name?

**Comment by kat** [comment]
@equivalentideas as we are implementing the network's interests that's not our call to make here. The network has already decided that wants to allow business people and have a very broad defnition of civil society interests. That's a given, and being the case, I think it better if people sign up with a business interest then we know about that than see them only as individuals. There's certainly acknowledgement that businesses have an interest in governments being more open accountable and transparent too.

**Comment by equivalentideas** [comment]
Ok cool @kat :ok_hand: 

So would the way to implement this be:

Remove the question: _If you are joining as a representative of an organisation, what’s its name?_

And instead have two questions:

### 1. What kind of member are you? (single option only)
- [ ] Individual
- [ ] Civil Society Organisation
- [ ] Business

### 2. If you are registering an organisation or business, what's it's name?

**Comment by kat** [comment]
Ok. Just careful if adapting the current form not to delete questions because I think that removes them from the resulting spreadsheet. (or copy the spreadsheet first).

**Comment by equivalentideas** [comment]
Done https://docs.google.com/forms/d/1Rwq8cLkSUQBRVin33QmMc2xwsgeA91DP_i5u3dLYIoA/viewform

> Just careful if adapting the current form not to delete questions because I think that removes them from the resulting spreadsheet. (or copy the spreadsheet first).

Amazingly Google Forms handled it really well :+1: all data retained.
