### ISSUE TITLE
in the theme discussion intro - make it obvious you have to join the network to join discussion

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#119]
if you jump straight to the theme discussion on a page it would be easy not to know you need to join the network before contributing to the discussion. This is something we fixed in the intro, but that's not the only entry point.

Suggested Fix: Include at least "To participate in this group, please first join the network." from https://groups.google.com/forum/#!forum/aogpn and include the link to the form.

**Comment by kat** [comment]
@craigthomler are you able to have a look at this one please? I don't seem to be able to edit the introductory message in each theme, and those messages are all authored by you.

**Comment by craigthomler** [comment]
Not today (traveling) - can do tomorrow.

On Tuesday, 16 February 2016, Kat notifications@github.com wrote:

> @craigthomler https://github.com/craigthomler are you able to have a
> look at this one please? I don't seem to be able to edit the introductory
> message in each theme, and those messages are all authored by you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AOGPN/opengovernment.org.au/issues/119#issuecomment-184465941
> .

## 

---

Craig Thomler

http://egovau.blogspot.com
http://twitter.com/CraigThomler
http://au.linkedin.com/in/craigthomler
http://www.slideshare.net/CraigThomler
http://www.slideshare.net/CraigThomler%20

_Mobile:_ 0411 780 194 (_International:_ +61 411 780 194)
_Phone:_ 02 6161 4508 (_International: *+61 2 6161 4508)
*Skype:_ craig.thomler

**Comment by craigthomler** [comment]
Done across all themes.
