### ISSUE TITLE
Add “Civil Society” to the site title

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#12]
Currently the website title is "AUSTRALIAN
OPEN GOVERNMENT PARTNERSHIP NETWORK". According to @kat’s [comment](https://github.com/AOGPN/opengovernment.org.au/issues/9#issuecomment-172734315):

> My recollection is that we agreed to keep Civil Society in the banner

So we should add that in somewhere. The title is getting very long already:

![screen shot 2016-01-18 at 5 32 51 pm](https://cloud.githubusercontent.com/assets/1239550/12384771/cccd9436-be09-11e5-99a2-e9171885aaf0.png)

Could the tagline that goes to the right on widescreens be a good place for this? See https://github.com/AOGPN/opengovernment.org.au/issues/10

**Comment by kat** [comment]
So to be clear, the idea is that "Civil Society" goes where it does in the UK site, in the main title of the network. I know it's too long, but it's the compromise we came up with given that the official name was too long already. I'm putting it in there for now, until we come up with a better alternative or a better name.

**Comment by kat** [comment]
I changed this in the general options 'site title' but it doesn't seem to have updated - it is set somewhere else or wrapping issue?

**Comment by equivalentideas** [comment]
> I changed this in the general options 'site title' but it doesn't seem to have updated - it is set somewhere else or wrapping issue?

It's actually part of the theme here https://github.com/AOGPN/opengovernment.org.au/blob/master/header.php#L54

**Comment by henare** [comment]
@equivalentideas instead of being hard coded should it read it from the WordPress site title?

**Comment by equivalentideas** [comment]
> @equivalentideas instead of being hard coded should it read it from the WordPress site title?

That can't happen easily because it has a <span> inside the text to style and layout the different words. We could pull front the site title and then use javascript to target the words we need and insert the styles, but that sounds really brittle and probably wouldn't help editors really. Or we could simplify the visual style.

I know you've discussed this with the network @kat , but it does still seem confusing to me to have a different name for the network in the site title. Users will assume that's the name of the network, but maybe that's the idea? I think I'm just missing the _why_ on this issue which makes it a bit harder to think up solutions.

**Comment by kat** [comment]
I'll try and expand on that earlier answer. 
- first -  please remember we're doing the dumb thing first - the title/name discrepancy is a contradiction the UK has lived with for a couple of years so I think we can live with it... especially in the interest of ... 
- second - It's important people know it's a CIVIL SOCIETY thing. The title is the most visible place to put it.
  I would already have it up there except that it's not set in the usual place. We come up with a better plan later.

**Comment by equivalentideas** [comment]
Thanks @kat that makes it super clear I think :+1:

So would something like this (which our image) be roughly what we're after?

![screen shot 2016-01-27 at 2 50 33 pm](https://cloud.githubusercontent.com/assets/1239550/12603294/8174222c-c505-11e5-9fa7-a27d003c2cdf.png)

**Comment by kat** [comment]
yes - terrific

kat@oaf.org.au
Founder, Director, Worker OpenAustralia Foundation
http://openaustraliafoundation.org.au/
openaustralia http://openaustralia.org/ | planningalerts
http://planningalerts.org.au/| electionleaflets
http://electionleaflets.org.au/ | righttoknow http://righttoknow.org.au/
| theyvoteforyou http://theyvoteforyou.org.au/

**Comment by equivalentideas** [comment]
Done in https://github.com/AOGPN/opengovernment.org.au/compare/977114bf12c0...677b70174e4d

![screen shot 2016-01-29 at 3 11 32 pm](https://cloud.githubusercontent.com/assets/1239550/12667037/bec87cae-c69a-11e5-9ca8-516473d8672a.png)
