### ISSUE TITLE
Replace Google Group with our forum

### ISSUE THREAD

**Issue by henare** [AOGPN/opengovernment.org.au#124]
We now have a Discourse forum setup (#5): https://forum.opengovernment.org.au/

So we need to transition from the Google Group to there.

**Comment by craigthomler** [comment]
Given there's been limited registrations & conversation, what will it take
to move across?

On Saturday, 5 March 2016, Henare Degan notifications@github.com wrote:

> We now have a Discourse forum setup (#5
> https://github.com/AOGPN/opengovernment.org.au/issues/5):
> https://forum.opengovernment.org.au/
> 
> So we need to transition from the Google Group to there.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AOGPN/opengovernment.org.au/issues/124.

## 

---

Craig Thomler

http://egovau.blogspot.com
http://twitter.com/CraigThomler
http://au.linkedin.com/in/craigthomler
http://www.slideshare.net/CraigThomler
http://www.slideshare.net/CraigThomler%20

_Mobile:_ 0411 780 194 (_International:_ +61 411 780 194)
_Phone:_ 02 6161 4508 (_International: *+61 2 6161 4508)
*Skype:_ craig.thomler

**Comment by henare** [comment]
I'm guessing:
- [x] Add site welcome message
- [x] Create new topics on Discourse to replace Groups threads
- [x] Update site with links to new forum topics
- [x] Replace embedded forum on get involved page
- [x] Tell people in the network about it
- [x] Start using it!

Anything else you can think of @craigthomler?

**Comment by henare** [comment]
> Replace embedded forum on get involved page

I've just removed it. The page does seem a bit bare without it. I'm open to ideas to fix that.

It looks like you can only [embed topics](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963) from Discourse, not the whole forum. That makes sense to me, embedding the whole forum seems like overkill.

**Comment by henare** [comment]
OK I've done everything but announce it!

**Comment by henare** [comment]
I spoke with Peter this morning and we discussed what needed to be done to announce the change.
- [x] Post a message to the (new) Group announcing the change
- [x] Close the (new) Group to further posts
- [x] Use Discourse to invite people on the (new) Group to the new forum
- [x] Email people who have signed up to be members but not joined the new forum, asking them to join
- [x] Email the (old) Group telling people about the new forum and asking them to join and contribute

He asked me to go ahead and do this as he's unable to do so himself right now.

**Comment by henare** [comment]
That's all done now! Fingers crossed people start participating :smile:
