### ISSUE TITLE
Markup of Manifesto post has a range of issues causing layout bugs and poor accessibility

### ISSUE THREAD

**Issue by henare** [AOGPN/opengovernment.org.au#131]
https://opengovernment.org.au/2016/06/09/towards-an-open-government-manifesto/

![selection_001](https://cloud.githubusercontent.com/assets/48945/15994901/ef50512a-3153-11e6-9fd1-6181518ae8a4.png)

**Comment by equivalentideas** [comment]
This will be caused by all the template markup in the body field of this post. It was copied out of one a special page template’s frontend preview into the normal new post creation page.

It has other issues as well like mixed up heading levels.

Stripping it all out is the way to go I think.

**Comment by equivalentideas** [comment]
- [x] Move ids to headings
- [x] Removes sections and div markup
- [x] fix link to google doc
- [x] Remove duplicate first heading 'Towards ...'
- [x] remove images around icon links
- [x] Fix heading levels
- [x] remove stray `<b>` tags

**Comment by equivalentideas** [comment]
Done.
