### ISSUE TITLE
Allow supporting organisations/people to show support by adding their names to reform area pages

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#135]
When the "case for action on reform on X" open letters are published, potential supporting organisations need a way to add their name to that issue. Also see #134

**Comment by kat** [comment]
To make contact, find out more, or express support for one or more areas that the government should take action on, and include in the first Australian Open Government Partnership National Action Plan:

1) respond to @ogpau 
2) email the ogpau email account 
3) contact individual IWG CS members, by twitter/email/phone? 

Not all members (3) will be available the whole time. Is there another way we can facilitate this (in the short term). 
- Invite comments on the page? 
- Add a form to sign up to show support one or more?(that's then handled by a person who adds the org/person's name to a list)

**Comment by equivalentideas** [comment]
One way to do this initially could be:

Add a button to the reform area page, “Add your support”. That links to Google Form with Name, email, and organisation name if it's on behalf of an organisation. We can ask them to email us their logo then.

There’s probably petition WordPress plugins that might make the experience more seamless for people, but this is an initial pass to get started.

**Comment by equivalentideas** [comment]
It would be nice to have a way for people to add an image.

**Comment by equivalentideas** [comment]
When people sign up we need a way to continue to contact them about the OGP and the network.

**Comment by equivalentideas** [comment]
We now have this in action on this page https://opengovernment.org.au/the-case-for-action-on-a-national-integrity-framework/
1. People click the “Add your name to support reform” button at the end of the text.
2. People subscribed to the responses get an email
3. Someone takes the the they enter and puts it onto the page.
4. They also email the person thanking them (https://github.com/AOGPN/opengovernment.org.au/issues/150)

**Comment by equivalentideas** [comment]
The form here https://drive.google.com/drive/u/0/folders/0B67Y_SEZzwGvUW42TXBBNk1NXzA can be copied and adapted for each reform area.

When you make a new page for a reform area, you can copy the markup at the bottom of this page https://opengovernment.org.au/the-case-for-action-on-a-national-integrity-framework/ and change the link to your new form.
