### ISSUE TITLE
Direct people to commitments overview from the homepage 

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#138]
The most important action for people to take now is to sign up to support reform in a commitment topic area https://github.com/AOGPN/opengovernment.org.au/issues/135

We should list these areas on the homepage, with a short excerpt of what/why you’d support this, and link to the letter/signup.

This would go above or replace the working groups section on the homepage.

To do this we need:
- a list of the topic areas
- roughtly 40 word text about each on
- pages to link to

**Comment by kat** [comment]
creating this page in  #153

**Comment by equivalentideas** [comment]
> We should list these areas on the homepage, with a short excerpt of what/why you’d support this, and link to the letter/signup.

As a first pass, lets just add a big section linking to the overview page (#153) on the homepage. And it should still replace the working groups section #142

**Comment by kat** [comment]
Do you mean the overview page should be a post? And that there should be an announcement linking to that from the homepage, rather than the overview page becoming the homepage? I'm not sure I understand the reasoning. Seems like more clicking for people to get to the intro & take action?

**Comment by kat** [comment]
@equivalentideas That said, if you're confident that's a good starting point, I'm happy to see how that goes if you want to implement. 💚

**Comment by equivalentideas** [comment]
I think this page could do with a TLDR upfront after the first sentence:

> The Australian Government has today presented its draft Open Government Partnership National Action Plan. This plan aims bring about practical changes that improve our society. And that’s a good thing.
> 
> Have a look at the draft commitments below and follow the links to read the detail and suggest improvements. (link)
> 
> There’s been a consultation process to get this far that started almost a year ago. Until now, only fairly small number of people have taken part in bringing together this draft Plan. Maybe you’re one of the people who took part in earlier phases of consultation and want to see what happened to ideas you put forward, or helped to bring together in an initial round of draft commitments? Maybe it’s the first you’ve heard of it?

**Comment by kat** [comment]
@equivalentideas you ok to remove that?

**Comment by equivalentideas** [comment]
> @equivalentideas That said, if you're confident that's a good starting point, I'm happy to see how that goes if you want to implement. 💚

Just to clarify things here’s what we could do:
1. Have a short section on the homepage linking to this page/post
2. Put all the content from this page onto the homepage.
3. Redirect the homepage to this page.

I think 2 seems good. But I'll do 1 first while I work out how to do that.

**Comment by equivalentideas** [comment]
☝️  Is that what you understood the plan to be @kat ?

**Comment by kat** [comment]
💯

**Comment by equivalentideas** [comment]
Cool.

**Comment by kat** [comment]
I was thinking 2. and thought you were suggesting 1. and if the intro is now too long, then please feel free to cull it ruthlessly.

**Comment by equivalentideas** [comment]
I'll just get it on there first. I'll make it so the content out of that page get's pulled to the homepage, so we can edit that page in the wp backend and it updates the homepage.

**Comment by equivalentideas** [comment]
Done, the full post is on the homepage https://opengovernment.org.au/

**Comment by equivalentideas** [comment]
I recon we should go for a more succinct title and cut down the intro a bit if possible.

> please feel free to cull it ruthlessly.

I'll have a go.

@kat I assume the _by Kat ..._ is some kind of disclaimer for the network? If not, I'm not sure it's useful for people. What do you recon?

**Comment by kat** [comment]
Yes, you could put it like that. Also showing my hand. I have been and am part of the process. It could go at the end or be a link on my name if you think that's better @equivalentideas It is a bit long

**Comment by kat** [comment]
Did you want to discuss title and content here or over in slack #ogp channel?

**Comment by kat** [comment]
@equivalentideas (optional - if you're feeling clear on what's essential and what can be dropped please go ahead)

**Comment by equivalentideas** [comment]
> Did you want to discuss title and content here or over in slack #ogp channel?

Here would be more open ;-) 

>  if you're feeling clear on what's essential and what can be dropped please go ahead

Yep I'll do a pass.

**Comment by kat** [comment]
👍

**Comment by equivalentideas** [comment]
I've done a bit of a cut and reorganise https://opengovernment.org.au/

Will call this closed.
