### ISSUE TITLE
Publish the first topic area page “The Case for Action on A National Integrity Framework”

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#147]
This first page is ”The Case for Action on A National Integrity Framework“ by Ken C.
- [x] Texted locked off
- [x] Clean up HTML
- [x] Petition link added “Add your support”
- [x] Published

**Comment by equivalentideas** [comment]
@kat a few questions about from the original text sent through, are indented sections blockquotes / quoting a passage of something?

e.g.

![screen shot 2016-10-24 at 12 51 45 pm](https://cloud.githubusercontent.com/assets/1239550/19631481/d374181c-99e8-11e6-9db3-439d9d477403.png)

Further down there's another indented section that could be a blockquote too. Are these two sections quotes? Can we link to/list a source? There's also underlined text, are these links?

![screen shot 2016-10-24 at 12 52 00 pm](https://cloud.githubusercontent.com/assets/1239550/19631482/d376d8d6-99e8-11e6-8eb4-1d891fb46914.png)

**Comment by kat** [comment]
thanks for your questions @equivalentideas I'll check the original document, Yes, the indented areas are a block quote. (my bad formatting).  and the underlined areas from memory didn't have links attached. I'll check.

**Comment by kat** [comment]
see original doc: [OpenAustralia Foundation case 4 action-National integrity framework.docx](https://github.com/AOGPN/opengovernment.org.au/files/546814/OpenAustralia.Foundation.case.4.action-National.integrity.framework.docx)

**Comment by equivalentideas** [comment]
Cheers, thanks really helpful.

Here's a preview of the page with cleaned HTML and the link to the form at the bottom https://opengovernment.org.au/?page_id=2834&preview=true

@kat here's some questions:
1. [ ] Are you happy with the title for the support section and link/button text?
2. [x] Reading this I really want links to those ART quotes. Also to the OGP grand challenge stuff. Should we add those now or leave it to Ken?
3. [x] I think this would be clearer with a more structure:
   1. short intro about what reform in this area would mean
   2. link to add your name
   3. “Case for” section
   4. list of names
   
   Are we interested in something like that now, or do we wanna get this live with the current structre and iterate?

**Comment by kat** [comment]
Good points/questions @equivalentideas , I've asked Ken to respond to these directly.

**Comment by equivalentideas** [comment]
I've published this, we can continue to change it for any more feedback https://opengovernment.org.au/the-case-for-action-on-a-national-integrity-framework/

**Comment by kat** [comment]
added the accountability roundtable URL where they're first mentioned, and changed page owner/author to Ken Coghill.

**Comment by kat** [comment]
Added introductory text from new version sent through "Reform in this area would reduce the risks of corruption of types and areas of government activity not caught by ACLEI’s current remit."

I don't believe there are other changes in the update, Ken to confirm.
