### ISSUE TITLE
Create first national action plan draft reform overview page

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#153]
Create an overview that 
- [x] brief introduction
- [x] lists the area headings - then...
- [x] lists all the draft commitments
  for each commitment
- [ ] overview for the case for each commitment
- [ ] link to support this reform and find out more

begin by copying and fleshing out [this template](https://docs.google.com/document/d/1cEIr2fG-YB4atvuUtoHm0qva2gPExPQBYyOgOoC-rdw/edit#)

**Comment by kat** [comment]
that's[ here](https://docs.google.com/document/d/1lnocEGLLyr6nzwJRqYmawvGhG6uXQAKc7rejHJ43laI/edit)

**Comment by kat** [comment]
The plan is out. First I'm updating commitment titles in the overview page

**Comment by kat** [comment]
Creating placeholder pages to link to and adding links to https://opengovernment.org.au/australias-first-open-government-draft-plan

**Comment by equivalentideas** [comment]
Looking good. I recon this should be a post not a page, so it comes up in the news feed etc.

**Comment by equivalentideas** [comment]
This is live and on the homepage https://opengovernment.org.au/ I'll close this. Reopen/rename if it's still being used.
