### ISSUE TITLE
Sydney Motorway Corporation should be subject to the GIPA Act (NSW)

### ISSUE THREAD

**Issue by Nouslepeuple** [AOGPN/opengovernment.org.au#158]
Sydney Motorway Corporation Pty Ltd replaced the WestConnex Delivery Authority (a NSW Government Agency) in 2015.  At that time it was no longer subject to the GIPA Act (freedom of information requests).  It has two government ministers as shareholders and carries out government projects such as WestConnex.  It acts at the direction of the government and correspondence to Ministers is routinely passed on to its employees/contractors to respond.  It is a defacto public service agency but is not subject to GIPA legislation.  It controls a project which will cost billions of public funds and which directly impacts on hundreds of thousands of people in Sydney yet its decisions, conduct and conflicts of interest are not able to be scrutinised and it is not accountable to the people of NSW.  Please help me in bringing about change so that Sydney Motorway Corporation is subject to the GIPA Act.

**Comment by henare** [comment]
Hi @Nouslepeuple, I'm from the [OpenAustralia Foundation](https://www.openaustraliafoundation.org.au/). We're members of the AOGPN and we helped [build the website](https://opengovernment.org.au/). As these issues are specifically about the website and not the OGP in general I'm going to close this issue. However I have some suggestions for you that I hope will help.

Although this iteration of Australia's OGP National Action Plan is focussed on the federal government, and the Sydney Motorway Corporation is associated with the NSW state government, I'd still suggest you get involved in the OGP process. You can read more about joining the AOGPN and getting involved here: https://opengovernment.org.au/get-involved/

For my next suggestion I need to make it clear that I'm suggesting this as someone from OpenAustralia Foundation and not on behalf of the AOGPN. The OpenAustralia Foundation run a project called [Right To Know](https://www.righttoknow.org.au/). It makes it simple for people to make requests for information to government and we make the whole process transparent. Despite Sydney Motorway Corporation not formally being subject to GIPA [we include them on Right To Know](https://www.righttoknow.org.au/body/smc) - this is deliberate and you can [read why on our site](https://www.righttoknow.org.au/help/requesting#authorities). I'd invite you to join us and make public requests to SMC on Right To Know to demonstrate a clear demand for more openness and accountability from this publicly funded organisation. Please don't hesitate to get in touch if you have any questions or if we can help: contact@righttoknow.org.au

**Comment by Nouslepeuple** [comment]
Many thanks for the information provided.
Regards
Catherine 


Sent on the go with Vodafone
-------- Original message --------From: Henare Degan <notifications@github.com> Date: 26/4/17  12:40  (GMT+10:00) To: "AOGPN/opengovernment.org.au" <opengovernment.org.au@noreply.github.com> Cc: Nouslepeuple <cge23005@bigpond.net.au>, Mention <mention@noreply.github.com> Subject: Re: [AOGPN/opengovernment.org.au] Sydney Motorway Corporation should
  be subject to the GIPA Act (NSW) (#158) 
Hi @Nouslepeuple, I'm from the OpenAustralia Foundation. We're members of the AOGPN and we helped build the website. As these issues are specifically about the website and not the OGP in general I'm going to close this issue. However I have some suggestions for you that I hope will help.
Although this iteration of Australia's OGP National Action Plan is focussed on the federal government, and the Sydney Motorway Corporation is associated with the NSW state government, I'd still suggest you get involved in the OGP process. You can read more about joining the AOGPN and getting involved here: https://opengovernment.org.au/get-involved/
For my next suggestion I need to make it clear that I'm suggesting this as someone from OpenAustralia Foundation and not on behalf of the AOGPN. The OpenAustralia Foundation run a project called Right To Know. It makes it simple for people to make requests for information to government and we make the whole process transparent. Despite Sydney Motorway Corporation not formally being subject to GIPA we include them on Right To Know - this is deliberate and you can read why on our site. I'd invite you to join us and make public requests to SMC on Right To Know to demonstrate a clear demand for more openness and accountability from this publicly funded organisation. Please don't hesitate to get in touch if you have any questions or if we can help: contact@righttoknow.org.au

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AOGPN/opengovernment.org.au","title":"AOGPN/opengovernment.org.au","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AOGPN/opengovernment.org.au"}},"updates":{"snippets":[{"icon":"PERSON","message":"@henare in #158: Hi @Nouslepeuple, I'm from the [OpenAustralia Foundation](https://www.openaustraliafoundation.org.au/). We're members of the AOGPN and we helped [build the website](https://opengovernment.org.au/). As these issues are specifically about the website and not the OGP in general I'm going to close this issue. However I have some suggestions for you that I hope will help.\r\n\r\nAlthough this iteration of Australia's OGP National Action Plan is focussed on the federal government, and the Sydney Motorway Corporation is associated with the NSW state government, I'd still suggest you get involved in the OGP process. You can read more about joining the AOGPN and getting involved here: https://opengovernment.org.au/get-involved/\r\n\r\nFor my next suggestion I need to make it clear that I'm suggesting this as someone from OpenAustralia Foundation and not on behalf of the AOGPN. The OpenAustralia Foundation run a project called [Right To Know](https://www.righttoknow.org.au/). It makes it simple for people to make requests for information to government and we make the whole process transparent. Despite Sydney Motorway Corporation not formally being subject to GIPA [we include them on Right To Know](https://www.righttoknow.org.au/body/smc) - this is deliberate and you can [read why on our site](https://www.righttoknow.org.au/help/requesting#authorities). I'd invite you to join us and make public requests to SMC on Right To Know to demonstrate a clear demand for more openness and accountability from this publicly funded organisation. Please don't hesitate to get in touch if you have any questions or if we can help: contact@righttoknow.org.au"}],"action":{"name":"View Issue","url":"https://github.com/AOGPN/opengovernment.org.au/issues/158#issuecomment-297221298"}}}
