### ISSUE TITLE
Update 'Get Involved'

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#17]
(via Craig) Get involved - Write content for how to get involved with the Australian Open Government Partnership Network

**Comment by equivalentideas** [comment]
I'm working on this in Google Docs here https://docs.google.com/document/d/16s-ABPy4qLRrqnULDiwHsLD9HKwHxwM86Nk7Cm_NF74/edit

**Comment by equivalentideas** [comment]
I've made a first pass on this section in that Google Doc, but I think it'll need some input from @kat when she's back before going any further.

**Comment by henare** [comment]
I've done a quick first pass at this.
