### ISSUE TITLE
Review Resources

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#19]
(via Craig) Hide the Resources section, or include the Accountability Roundtable paper (if releasable) and link to OGPNet resources.

**Comment by henare** [comment]
> Hide the Resources section

Let's do this for now.

**Comment by equivalentideas** [comment]
I've removed 'Resources' from the site menu and set all the resources to _draft status_ so that if we want to keep any of the OGP generic ones we can. You can add and edit resources here https://opengovernment.org.au/wp-admin/edit.php?post_type=resource&mode=list&paged=1
