### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#20]
Add upcoming Network meetings and any more government run sessions to http://www.opengovernment.org.au/events/

**Comment by henare** [comment]
I've added the Government's past information sessions. I'm going to assign this to @kat to see if you want to [add](https://opengovernment.org.au/wp-admin/edit.php?post_type=event) the AOGPN foundational meeting. I'd like to see it there for posterity and so people get a sense of the community doing stuff.

**Comment by kat** [comment]
When we post upcoming events from the perspective its interest to civil society - 
- let civil society know when they need to take action 
- respond to the government
  or with analysis of government announcements

Backfilling past events suggests that the site existed before it did, so let's not do that unless its in the form of a 'story so far' round up.

**Comment by henare** [comment]
I think this is all done.
