### ISSUE TITLE
Thank UK people for letting us use their theme, etc.

### ISSUE THREAD

**Issue by henare** [AOGPN/opengovernment.org.au#22]

**Comment by henare** [comment]
Where should we put this?

**Comment by equivalentideas** [comment]
Maybe a section at the bottom of the about page? Also the README?

**Comment by henare** [comment]
> Maybe a section at the bottom of the about page?

Yes! That makes sense.

> Also the README?

Good call. We should link to this repo on the site too.

**Comment by equivalentideas** [comment]
Added a section about the website with links to all the repos and thanks to the about page https://opengovernment.org.au/about/#section-3

**Comment by equivalentideas** [comment]
And added it to the readme https://github.com/AOGPN/opengovernment.org.au/commit/e3f9bfa492b6bfdf3ccd703c2cf8d86b11a29beb

Feel free to go ahead and tweak the text in both places :pencil2:
