### ISSUE TITLE
Add terms of reference

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#24]
Australian Open Government Partnership Network  V2
Table of contents
1. Introduction
2. Purpose
3. Membership
4. Principles
5. Steering committee
6. Coordinator
7. Decision Making
Annex A: Open Government Declaration
1. Introduction
The Australian Open Government Partnership Network (AOGPN) is a coalition committed to making government work better by promoting transparency, open government, public participation and deliberation and accountability.
This document sets out the AOGPN’s terms of reference, as agreed on …
These terms of reference will be reviewed every two years, at the initiative of the AOGPN Steering Committee.
2. Purpose
The AOGPN was formed in response to the Australian government decision in November 2015 to join the Open Government Partnership, with a focus on engaging with the development and review of Australia’s first and subsequent Open Government National Action Plans.
The AOGPN aims to mobilise and coordinate public advocacy for government and other public institutions to work better by promoting transparency, open government, public participation and deliberation and accountability.
The AOGPN has a primary focus on the development and implementation of ambitious open government reforms through Australian membership of the Open Government Partnership. The AOGPN combines a collaborative approach by key stakeholders in the National Action Plan process, with a role also to challenge and hold government to account for ambitious commitments and action to deliver them.
In addition, the AOGPN works to support greater collaboration across Australia on open government reforms and constitutes a resource of people, ideas and capacity on which new or existing projects that share its aims can draw.
3. Membership
Membership is open to any individual or organisation, on the condition that they:
1. Endorse the Open Government Declaration (see annex A)
2. Abide by the Network’s principles
3. Have no conflicts of interest. Conflicts of interest include, but are not limited to being:
● a government minister or shadow minister
● a political advisor working with government ministers or shadow ministers
● a government official working on open government policy
● a corporate lobbyist (e.g. an individual lobbying for a private interest, potentially in conflict with the Open Government Declaration or AOGPN principles)

 Individuals join the AOGPN by signing up to the list on the Open Government Forum. Membership of that list is taken as assent to and compliance with the above conditions.
Members may choose to be associated with, and act as the representative of an organisation by indicating this on their list profile and in their statements in network activities, but only insofar as the stated goals of that organisation are working towards the public (rather than private) interest and are compatible with AOGPN principles.
Membership rights include being on the mailing list, attending meetings, contributing to  work on OGP, and nominating members of the Steering Committee.
1. Principles
   When taking part in the activities of the AOGPN, members should abide by the following principles:
2.  To act in the public interest and for public not private or commercial purposes
3.  To take decisions impartially, fairly and on merit, using the best evidence and without discrimination or bias.
4.  To be accountable for your decisions and actions.
5.  To take decisions in an open and transparent manner. Information should not be withheld from the public unless there are clear and lawful reasons for so doing.
6.  To promote and support the principles.

Members of AOGPN should engage constructively with the activities of the AOGPN, and are encouraged to participate in public debate whether or not their views are consistent with the AOGPN.

 Members may represent themselves as being part of the network, but cannot speak on its behalf.
1. Steering Committee
   The Steering Committee has responsibility for:
   ● Engaging with government representatives with responsibility for the OGP and with parliamentarians and others with an interest in the OGP and related issues. 
   ● Speaking on behalf of the AOGPN.
   ● Supporting and overseeing the work of the Convener and ensuring the smooth running of the network.
   ● Expanding the membership and reach of the AOGPN.
   ● Where necessary, making decisions on behalf of the AOGPN (see section 7)

The Steering Committee will meet at least once every quarter.
The Steering Committee will be made up of no fewer than 5 and not more than 9 members drawn from the membership. This must include a balance of individual citizens and representatives of organisations and a gender balance 
Half of the Steering Committee places will be put up for reselection every year. Incumbents may be reselected, but individuals may only sit for up to 4 years before being required to step down. An individual may subsequently be reselected following 2 years of not sitting.
When places on the Steering Committee become available, nominations will be sought from members for new committee members.

Query-voting members?
A member can nominate or be nominated by another member. Selection will be conducted through a ballot of those members who represent organisations and who are members at the time of the election.
 Steering Committee members have a particular responsibility to abide by and exhibit the AOGPN principles. A member who does not abide by the principles can be required to step down by the Steering Committee by a ⅔ majority vote.
6. Convener
The Convener has responsibility for:
● Administering and coordinating the network.
● Expanding the membership. 
● Engaging with relevant government officials and others with responsibility for the OGP.
● Publicising the work of the OGN.

The Convener is selected by and works on the behalf of the network and has a particular responsibility to abide by and exhibit its principles.
The Convener is appointed by the Steering Committee and subject to performance review by the committee.
The Convener with support from the Steering Committee and wider network, is responsible for securing the necessary funding for the network.
7. Decision Making
The AOGPN seeks to operate through a process of consensus decision making. 
Any documents, public statements or positions adopted should clearly describe the basis on which they are made.
Four main methods of decision making and public statement are proposed:
Network consensus
Where a text has been open for discussion by the network for at least two weeks, and the draft text itself has been posted to the network mailing list for not less than one week, with a clear statement to the effect that it is proposed as a network decision.
Consensus will be deemed to be reached in the event of (a) no objections or modifications to the text being suggested during that period; (b) all those who have raised objections or suggested modifications being satisfied that their views have been taken into account. 
Network consensus should be used for strategic decision making by the network. 

Network signatures
Where a text has been put forward, and network members are invited to add their signatures to that statement, either as individuals, or on behalf of their organisations. 
Texts of this form should be presented as coming from 'Members of the Australian Open Government Partnership Network'.
This process can be combined with network consensus, to allow for a text to be presented as 'A position of the Australian Open Government Partnership Network'
Where sub-groups are formed (e.g. for dialogue with specific government departments), these groups should be clear that they are speaking as a group of members of the Network, and not on behalf of the Network, unless they have a mandate through a consensus process. 
Steering Committee vote
If consensus is not possible due to timescales, the Steering Committee may make decisions on behalf of the Network by a vote, fully taking into account any and all available evidence as to the views of Network members. 
Any such Steering Committee decisions shall be communicated to the Network mailing list, and shall be communicated publicly as a statement of the 'Steering Committee of the Australian Open Government Partnership Network'.
Wherever possible, the Steering Committee should bring issues to the network for consensus discussion.
Convener 
The Convener may make such operational day-to-day decisions as are required, liaising with the Steering Committee as and when required, and report to the committee and the broader membership on a regular basis.

Annex A: Open Government Declaration
September 2011
As members of the Open Government Partnership, committed to the principles enshrined in the Universal Declaration of Human Rights, the UN Convention against Corruption, and other applicable international instruments related to human rights and good governance:
We acknowledge that people all around the world are demanding more openness in government. They are calling for greater civic participation in public affairs, and seeking ways to make their governments more transparent, responsive, accountable, and effective. 
We recognize that countries are at different stages in their efforts to promote openness in government, and that each of us pursues an approach consistent with our national priorities and circumstances and the aspirations of our citizens.
We accept responsibility for seizing this moment to strengthen our commitments to promote transparency, fight corruption, empower citizens, and harness the power of new technologies to make government more effective and accountable. 
We uphold the value of openness in our engagement with citizens to improve services, manage public resources, promote innovation, and create safer communities. We embrace principles of transparency and open government with a view toward achieving greater prosperity, well-being, and human dignity in our own countries and in an increasingly interconnected world. 
Together, we declare our commitment to:
Increase the availability of information about governmental activities.
Governments collect and hold information on behalf of people, and citizens have a right to seek information about governmental activities. We commit to promoting increased access to information and disclosure about governmental activities at every level of government. We commit to increasing our efforts to systematically collect and publish data on government spending and performance for essential public services and activities. We commit to pro-actively provide high-value information, including raw data, in a timely manner, in formats that the public can easily locate, understand and use, and in formats that facilitate reuse. We commit to providing access to effective remedies when information or the corresponding records are improperly withheld, including through effective oversight of the recourse process. We recognize the importance of open standards to promote civil society access to public data, as well as to facilitate the interoperability of government information systems. We commit to seeking feedback from the public to identify the information of greatest value to them, and pledge to take such feedback into account to the maximum extent possible. 

Support civic participation.
We value public participation of all people, equally and without discrimination, in decision making and policy formulation. Public engagement, including the full participation of women, increases the effectiveness of governments, which benefit from people’s knowledge, ideas and ability to provide oversight. We commit to making policy formulation and decision making more transparent, creating and using channels to solicit public feedback, and deepening public participation in developing, monitoring and evaluating government activities. We commit to protecting the ability of not-for-profit and civil society organizations to operate in ways consistent with our commitment to freedom of expression, association, and opinion. We commit to creating mechanisms to enable greater collaboration between governments and civil society organizations and businesses.
Implement the highest standards of professional integrity throughout our administrations.
Accountable government requires high ethical standards and codes of conduct for public officials. We commit to having robust anti-corruption policies, mechanisms and practices, ensuring transparency in the management of public finances and government purchasing, and strengthening the rule of law. We commit to maintaining or establishing a legal framework to make public information on the income and assets of national, high ranking public officials. We commit to enacting and implementing rules that protect whistleblowers. We commit to making information regarding the activities and effectiveness of our corruption prevention and enforcement bodies, as well as the procedures for recourse to such bodies, available to the public, respecting the confidentiality of specific law enforcement information. We commit to increasing deterrents against bribery and other forms of corruption in the public and private sectors, as well as to sharing information and expertise. 
Increase access to new technologies for openness and accountability.
New technologies offer opportunities for information sharing, public participation, and collaboration. We intend to harness these technologies to make more information public in ways that enable people to both understand what their governments do and to influence decisions. We commit to developing accessible and secure online spaces as platforms for delivering services, engaging the public, and sharing information and ideas. We recognize that equitable and affordable access to technology is a challenge, and commit to seeking increased online and mobile connectivity, while also identifying and promoting the use of alternative mechanisms for civic engagement. We commit to engaging civil society and the business community to identify effective practices and innovative approaches for leveraging new technologies to empower people and promote transparency in government. We also recognize that increasing access to technology entails supporting the ability of governments and citizens to use it. We commit to supporting and developing the use of technological innovations by government employees and citizens alike. We also understand that technology is a complement, not a substitute, for clear, useable, and useful information. 
We acknowledge that open government is a process that requires ongoing and sustained commitment. We commit to reporting publicly on actions undertaken to realize these principles, to consulting with the public on their implementation, and to updating our commitments in light of new challenges and opportunities. 
We pledge to lead by example and contribute to advancing open government in other countries by sharing best practices and expertise and by undertaking the commitments expressed in this declaration on a non-binding, voluntary basis. Our goal is to foster innovation and spur progress, and not to define standards to be used as a precondition for cooperation or assistance or to rank countries. We stress the importance to the promotion of openness of a comprehensive approach and the availability of technical assistance to support capacity- and institution-building.
We commit to espouse these principles in our international engagement, and work to foster a global culture of open government that empowers and delivers for citizens, and advances the ideals of open and participatory 21st century government.

**Comment by henare** [comment]
It looks like "About" would be the right section for this.

**Comment by equivalentideas** [comment]
> It looks like "About" would be the right section for this.

Sounds good. On it’s own page?

**Comment by henare** [comment]
:+1: I'd say.

**Comment by equivalentideas** [comment]
I'm going to add this by turning the text above into markdown and then posting that. You've got v2 in the title, which makes me think this version is more up to date than https://docs.google.com/document/d/12LlWl0jW3oINDmV3FSrckxUw4DvketSlXJJaa0mxlZw/edit#heading=h.30j0zll

**Comment by equivalentideas** [comment]
I've copied this into the site. Ended up turning it into nice markdown but then copying in the html as we don't have a markdown conversion plugin yet. It seemed messy to do it in markdown without getting the actually site editors involved first. They might need to use the visual editor.

**Comment by equivalentideas** [comment]
View it here https://opengovernment.org.au/about/terms-of-reference/#steering-committee
