### ISSUE TITLE
Let people sign up to google group

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#25]
Part of "get involved"?

**Comment by henare** [comment]
It's linked in the header nav as "forum". I think we should change that label - "Discussion" perhaps?

@kat was there anything else you had in mind for this issue?

**Comment by kat** [comment]
@henare I didn't put 2+2 together here and wasn't thinking about replacing the forum page there. Assuming we're just using the google group how about having a sign up equivalent to [this dialogue](http://codeforaustralia.us7.list-manage.com/subscribe?u=c5326c963a6f72c18f116c714&id=aac8d99517) Perhaps linked from the place the forum would be linked to from https://opengovernment.org.au/engage/open-government-network/ If that seems like a good first pass, then we can remove the forum header nav for now.

**Comment by henare** [comment]
@kat I like it :+1: So we need to:
- [x] Update get involved page, including details of how to get on the Google Group (actually #17)
- [ ] Fix/work around #38
- [x] Remove forum link from header nav

**Comment by henare** [comment]
I've done the two main things for this and #38 is still outstanding as its own issue so I'm going to close this now.
