### ISSUE TITLE
Site name is too long on very small screens

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#3]
The site name "Australian Open Government Partnership Network" doesn't fit into the current layout allocated on small screens. We can adjust the text or change the layout/style.

![screen shot 2016-01-18 at 5 35 57 pm](https://cloud.githubusercontent.com/assets/1239550/12384800/072b6112-be0a-11e5-8246-7f7b74f0fde8.png)

**Comment by henare** [comment]
> We can adjust the text or change the layout/style.

I don't think we're changing the text so we should change the layout/style.

**Comment by equivalentideas** [comment]
I fixed this in e5980cd by allowing the name to wrap around and the navbar to stretch to include the taller element.

![screen shot 2016-01-25 at 11 50 17 am](https://cloud.githubusercontent.com/assets/1239550/12540254/dd5795ae-c359-11e5-884c-eb9e8d4b714a.png)
