### ISSUE TITLE
Expand bold on logo text to "Australian Open Government"

### ISSUE THREAD

**Issue by henare** [AOGPN/opengovernment.org.au#34]
At the moment we're just emphasising "Australian" but that doesn't really say much about what this is all about. Expanding the bold to "Australian Open Government" gives you a quick sense of what this is about and hopefully won't overwhelm the rest of the logo.

**Comment by equivalentideas** [comment]
I like this thinking, but do you think it's an issue that the name then is visually broken into two groups:

> Australian Open Government, Partnership Network

It sounds like we're the Partnership Network for Australian Open Government.

**Comment by henare** [comment]
Yeah good point. Hmm...

**Comment by equivalentideas** [comment]
Since this logo text has now changed to the full 'AUSTRALIAN OPEN GOVERNMENT PARTNERSHIP CIVIL SOCIETY NETWORK', I don't think this quite specific change is relevant. Please reopen if you disagree :)
