### ISSUE TITLE
Replace current *Terms of reference* with latest version

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#35]
This issue is now about replacing the current _Terms of reference_ with latest version.

See comments below https://github.com/AOGPN/opengovernment.org.au/issues/35#issuecomment-175547685

<del>In the [Steering committee section](https://opengovernment.org.au/about/terms-of-reference/#steering-committee) of the [Terms of reference](https://opengovernment.org.au/about/terms-of-reference/), it says:</de>

> <del> Query-voting members?</de>

<del>This appears to be a note to the editors @kat ?</del>

**Comment by kat** [comment]
This seems like an error, so I've changed this to a subheading and removed the word "Query" for the time being. I'll leave the issue open until I get confirmation from Peter Timmins that this is right.

**Comment by kat** [comment]
(via Peter) here are latest and agreed version of the Terms of reference. Confusingly this is named -1 and the other one is v2. We need to replace the text with this one. 
[AOGPN Terms of Reference -1.docx](https://github.com/AOGPN/opengovernment.org.au/files/106428/AOGPN.Terms.of.Reference.-1.docx)

**Comment by equivalentideas** [comment]
For those without Word I've put that [new version (v1)](https://docs.google.com/document/d/1ptyv4b1iUY5Q_AiyTpelmX-00k8oPUhCq6zgv--fR6Y/edit) in google docs too

**Comment by kat** [comment]
I'm not sure this has been approved by the network, and I have some questions about changes that have been made. Changes to be implemented pending network review

**Comment by equivalentideas** [comment]
This is something the steering committee needs to work out so doesn't need to be on the [Open site milestone](https://github.com/AOGPN/opengovernment.org.au/milestones/Open%20site). I'm removing it from the milestone and adding it to [Launch](https://github.com/AOGPN/opengovernment.org.au/milestones/Launch).

I've also added a notice and link to this issue at the top of [the page on WordPress](https://opengovernment.org.au/about/terms-of-reference/).

**Comment by henare** [comment]
Peter advises that the changes were accepted. So we can close this I think.

**Comment by henare** [comment]
@equivalentideas says we may need to update the page. Reopening and assigning to him.

**Comment by equivalentideas** [comment]
As I understand it, it's “V1” version https://docs.google.com/document/d/1ptyv4b1iUY5Q_AiyTpelmX-00k8oPUhCq6zgv--fR6Y/edit that has been approved. “V2”, the older version, is what's on the site so I'll make that swap.

**Comment by equivalentideas** [comment]
Ok I've updated it here https://opengovernment.org.au/about/terms-of-reference/
