### ISSUE TITLE
Make site introduction text more succinct and helpful to new users

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#36]
When people come to the site for the first time, after googling "OGP Australia" for example, they need to know the answer to the simple questions “what’s this all about?”, “what does this network actually do?”

Currently the big text introducing the network to people reads:

> ## For better, open government
> 
> We are a network of individuals and organisations committed to helping governments work better by promoting transparency, open government, public participation, deliberation and accountability. Formed following the Australian Government’s decision to join the Open Government Partnership, we support this goal through information-sharing and working cooperatively to help government set and meet ambitious and achievable open government reforms.

![screen shot 2016-01-25 at 4 22 50 pm](https://cloud.githubusercontent.com/assets/1239550/12543206/2a442d88-c381-11e5-85f4-9f0a0fd4fa2c.png)

In issue #4 I raised the problem that this text is very repetitive in meaning with the text in the site header:

> AUSTRALIAN OPEN GOVERNMENT PARTNERSHIP NETWORK
> Making government work better for people through transparency, participation and accountability

I think that's basically a more succinct version of the first sentence of our intro par. This is an opportunity to help people understand what the network really does, so that they can hopefully get involved or at least just understand all our posts in context.

As @henare [says](https://github.com/AOGPN/opengovernment.org.au/issues/4#issuecomment-173811597):

> So that new people coming to the site actually understand what AOGPN is we need to make sure it's not just about the AOGPN values but also who we actually are and what we actually do. So often I find myself reading things like about pages and still having no freaking clue what the organisation is or does :smiley:

**Comment by equivalentideas** [comment]
I think the improvements we make here can also be used in the short footer introduction to the network. From #11 :

> This section seems very similar in purpose to the homepage introduction section to me: To give people who have come to any page on the site (a news update or event via twitter for example) some quick context about what the network is and does and give them a next step to get involved. I'm going to suggest we wrap the improvement of the text in the section with the issue about improving the homepage intro text #36 .

![screen shot 2016-01-25 at 5 14 42 pm](https://cloud.githubusercontent.com/assets/1239550/12543858/fe6ed6c0-c387-11e5-8bd6-b7b1a260f9f4.png)

**Comment by equivalentideas** [comment]
We decided that this was ok for the [Open site](https://github.com/AOGPN/opengovernment.org.au/milestones/Open%20site) milestone for people inside the steering committee to see, but will need to be closed before [Launch](https://github.com/AOGPN/opengovernment.org.au/milestones/Launch), when the site is more widely promoted.

**Comment by equivalentideas** [comment]
This text is also on the introduction to the membership form and should be fixed before it gets sent round to the people in the google group #76

**Comment by kat** [comment]
The UK wording was more concise but no more user centred.

'The UK Open Government Network collaborates with and challenges governments in the UK to develop and implement ambitious open government reforms through the UK’s membership of the Open Government Partnership.'

Just popping back here as a starting point briefly in this conversation.

**Comment by equivalentideas** [comment]
I'm working on this in a google doc here https://docs.google.com/document/d/14nO_HtryBL_Sitc5JFMKr3gWVWpMrFZkt33UrVNj5DA/edit

**Comment by equivalentideas** [comment]
Ok I've got a first pass at this that's focused on why you'd wanna join, and what we do:

> ## For better, open government
> 
> Across the globe civil society networks are using the Open Government Partnership process to achieve real gains in openness, accountability and participation. We are a diverse civil society coalition working together to create ambitious commitments for Australia’s first OGP National Action Plan.
> 
> Join us (links to ‘get involved’ rather than ‘about’)

I think the title could be more about what we do, but can think of anything better at this point.

**Comment by equivalentideas** [comment]
> Ok I've got a first pass at this that's focused on why you'd wanna join,

I'm pretty happy with that :point_up:. I'm going to put it up as the next iteration and we can continue to improve it from here.
