### ISSUE TITLE
Give me some quick ways to do something with the network instead of repeating 'lastest posts'

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#37]
When people hit the homepage they're probably just learning about the network and exploring the site. As @henare says on #4 , a likely situation is :

> someone comes to the home page either wanting to find out what this is all about or hits the home page but wants to quickly go to some other specific page.

Currently in the row at the very top of the homepage we've got a simplified version of the 'Latest updates' from further down the page:

![screen shot 2016-01-25 at 4 47 04 pm](https://cloud.githubusercontent.com/assets/1239550/12543450/ab24c7bc-c383-11e5-9e66-f13e377678ca.png)

On #4 I posted:

>  The stripped back latest posts on the right is doing no where near as good a job of grabbing my attention and giving context as the more filled out version further down the page.

and @henare brilliantly suggested:

> How about instead of News we have ways people can get involved. So the idea would be to give people enough information in the new, meaty summary section that they're informed and excited enough to want to get involved?

I think that's a great idea. So what are some ways that people can get involved with the network?
- They could join the dicsussion throught the Google Group
- They could come and meet us at our events or general OGP events

What else? Anything simple and quick that could give them an easy way in? Ping @kat :smile:

Once we work out a list of things I think we refine that to two or max three things.

**Comment by henare** [comment]
@kat's suggestion from a discussion just now is to add the next key date, similar to #47.

**Comment by kat** [comment]
... and also 'what you can do now' ie which phase of the consultation process we're in and how you can have input

**Comment by equivalentideas** [comment]
> ... and also 'what you can do now' ie which phase of the consultation process we're in and how you can have input

... including link to the timeline.

**Comment by equivalentideas** [comment]
We've now replaced that section with a notice about the Prime Ministers letter on this issue to make sure people know this is a _real thing_ with high level support.

I'm gonna close this as this idea would have to change quite a bit to be implemented now.
