### ISSUE TITLE
Google Groups subscribe link doesn't work

### ISSUE THREAD

**Issue by henare** [AOGPN/opengovernment.org.au#38]
When you visit the Groups page and click "Subscribe to this group" it does nothing: https://groups.google.com/forum/#!forum/ogpaustralianetwork

**Comment by henare** [comment]
I've reported it to Google but who knows if that will help. I think we need to provide a workaround in the mean time.

**Comment by kat** [comment]
that does seem to work for me. If logged in with an email account which isn't the one I'm a member of this group with it tells me I need to apply for membership. Have another look and see if it works for you @henare

**Comment by henare** [comment]
@kat thanks for checking this. I think it's only when you're completely logged out. Since it was working for you I'll close this. If it's still a problem we can reopen it.
