### ISSUE TITLE
Add a description of what this website is meant to do and who it is for somewhere

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#39]
Working through these issues I think it's time to document the purpose of this project and who it's meant to serve. This could just be a few sentences in the readme—anywhere we can point to as a decision making tool.

You can see the usefulness of this in issue #4 where the discussion edges back to these questions and then leads to a decision.

Since the network has a bunch of people around the country contributing to this project, I think it will speed up decision making if we just jot down what some of our assumptions are.

**Comment by henare** [comment]
@equivalentideas do you have some examples of other projects where this is done effectively? I think that would help other people understand what you're proposing and why.

**Comment by equivalentideas** [comment]
> @equivalentideas do you have some examples of other projects where this is done effectively? I think that would help other people understand what you're proposing and why.

I'm going to close this. I think I'm just in a bad head space and am throwing up solutions without being able to articulate a problem.

**Comment by kat** [comment]
Re-opening - This informs everything we do!

**Comment by equivalentideas** [comment]
Here's the description of what the Network does that we came up with yesterday:

> Create a set of ambitious action plan commitments that address the key challenges we face in Australia

The OGP describes the purpose of working groups as:

> to support the creation and effective implementation of more ambitious open government commitments as part of OGP national action plans.

I like that the OGP one includes implementation, the actual “doing”.

Here's a mashup of the two:

> We create and support the implementation of ambitious OGP action plan commitments that address the key challenges we face in Australia

So the purpose of this website in the lead up to the first action plan could be:

> Help the Network create ambitious OGP action plan commitments that address the key challenges we face in Australia.

It does this by:
1. being a workspace for network members to develop and present ambitious action plan commitments
2. helping people learn about, join and coordinate working groups
3. attracting and enabling a diverse set of people to join the Network

I'm going to chuck that in as a starting point and we can improve it from there.

**Comment by equivalentideas** [comment]
We'll put this in the readme and also in [the _This website_ section of the About page](https://opengovernment.org.au/about/#section-3).

**Comment by equivalentideas** [comment]
I've added this to the [About page](https://opengovernment.org.au/about/#section-3) and [the readme](https://github.com/AOGPN/opengovernment.org.au/blob/master/README.md). I think the prioritised this of ways it achieves it's purpose could be made more specific, but it's a starting point.

## README

![screen shot 2016-01-29 at 11 30 05 am](https://cloud.githubusercontent.com/assets/1239550/12663371/d273b332-c67b-11e5-8edb-de600542aada.png)

## About page

![screen shot 2016-01-29 at 11 29 58 am](https://cloud.githubusercontent.com/assets/1239550/12663370/d244f858-c67b-11e5-98c6-c434b1f10ac2.png)
