### ISSUE TITLE
"News and blog" and "Updates" sections are duplicates

### ISSUE THREAD

**Issue by henare** [AOGPN/opengovernment.org.au#40]
https://opengovernment.org.au/news-blog/ seems to list all blog posts.

https://opengovernment.org.au/updates/ lists them by category.

Listing by category was needed when there was all the country updates but we've removed that because we don't need it.

I think we should just get rid of one of these. Maybe remove "updates" and rename "news & blog" to just "news" ("blog" is a bit old skool and jargony).

**Comment by equivalentideas** [comment]
> I think we should just get rid of one of these. Maybe remove "updates" and rename "news & blog" to just "news" ("blog" is a bit old skool and jargony).

That sounds good to me. “News & Notes” might be a nicer description since it will probably include opinion and other stuff?

**Comment by henare** [comment]
Okay, I'll use that as the title but keep the URL as just "/news".

**Comment by equivalentideas** [comment]
> Okay, I'll use that as the title but keep the URL as just "/news".

Nice :+1:
