### ISSUE TITLE
Resolve question in About page text

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#41]
In the third paragraph of the ['The Australian Open Government Network' section of the about page](https://opengovernment.org.au/about/#section-2), there is a question in the text:

> The membership of the network currently stands at o ?? members.

Let's resolve this :)

![screen shot 2016-01-27 at 11 49 06 am](https://cloud.githubusercontent.com/assets/1239550/12600260/5d7f1d9a-c4ec-11e5-8075-a976d39d7348.png)

**Comment by kat** [comment]
51 as of just now.

**Comment by kat** [comment]
seems like a bit of a pain to keep updating that though... I guess it's just a rough number to show people who aren't part of it yet the scale of it.

**Comment by equivalentideas** [comment]
What about “The network already has over 50 members.” ?

**Comment by kat** [comment]
better make it 50, henare's in twice. Updated.
