### ISSUE TITLE
Provide a way for the network to communicate

### ISSUE THREAD

**Issue by henare** [AOGPN/opengovernment.org.au#5]
To keep things simple our plan for this initial setup is to just copy what the UK has. They have [a forum](http://forum.opengovernment.org.uk/), based on [Lumen](http://wordsandwriting.github.io/lumen/), so we were going to set that up too.

Again, to keep things simple we were just going to put it on our server for the time being. However after looking at Lumen it's clear that it's [very](https://github.com/wordsandwriting/lumen/blob/master/app/controllers/config.rb#L130-L152) [tightly](https://github.com/wordsandwriting/lumen/blob/master/app/controllers/config.rb#L117-L118) [integrated](https://github.com/wordsandwriting/lumen/blob/master/models/group.rb#L260-L279) [with](https://github.com/wordsandwriting/lumen/blob/master/models/group.rb#L281-L316) its expected deployment environment, i.e. Heroku with a separate VPS running Virtualmin.

For this reason I don't think it's feasible to run it in a different hosting environment without significant changes. Making significant changes is definitely not something we can afford to do right now even if we wanted to.

So that's made me reassess what we're trying to do and why we're doing it. I've outlined several options for what we could do below.
### Use Lumen

It's not feasible to put Lumen on our existing server. It needs its own VPS for mail, etc. and the web application needs to be deployed to Heroku. So the first disadvantage is the cost of the VPS at least and possibly Heroku. This is likely around to be $20/month.

Advantages:
- Copying what the UK's got is the simple thing to decide to do
- AOGPN would have its own server
- It's a web forum
- It works over email

Disadvantages:
- Cost of VPS/Heroku
- Cost of managing another server
- ...i.e. AOGPN would have its own server
- Lumen pretty hacky - a pain to maintain?
### Use Google Groups

Instead of creating something new we could just continue to use Google Groups for all discussion. We could also just do this for the time being, until we decide we need something else.

Advantages:
- Nothing to do

Disadvantages:
- Many people don't like Groups for very good reasons, e.g. it's not open it's Google, the UX of the Groups interface is terrible
- It doesn't have separate groups, it's just one mailing list
- That also means you can't have private groups (is that something we want?)
### Use Discourse

Instead of Lumen @equivalentideas suggested we could use [Discourse](http://www.discourse.org/). It's the best modern web forum software and we use it [elsewhere](https://help.morph.io/).

Advantages:
- It's a modern web forum

Disadvantages:
- ~~It doesn't work over email~~

@maxious writes:

> OKFN uses Discourse and I do get emails just like google groups that you can reply to https://discuss.okfn.org/t/enable-mailing-list-capabilities-of-discourse/219 https://meta.discourse.org/t/new-reply-via-email-support/7764 or even start new threads https://discuss.okfn.org/t/testing-out-starting-a-topic-via-email/1183/3
- Needs a server. We could probably get it working on our server but I've only ever deployed it using the Docker image
### Use something else

Could something like [Loomio](https://www.loomio.org/) be useful for discussions and decisions for our network?

---

I think the most useful feedback on this issue will come from the people that understand our requirements, so I'll ask for feedback from @kat and Peter to start with.

**Comment by equivalentideas** [comment]
Great job @henare . What do you mean that some of them “work over email” and some don't? I'm not sure if that is clear for people who haven't used some of these.

**Comment by henare** [comment]
@equivalentideas work over email == like Google Groups. If people choose they can use it exactly like a mailing list and do everything in their email.

This is opposed to web forums like Discourse where you are notified of new items by email but you have to click the link to visit the site to reply to messages, etc.

**Comment by equivalentideas** [comment]
Thanks @henare :ok_hand: that's clear.

**Comment by henare** [comment]
I just spoke to @kat and given she's just about to meet lots of amazing people with experience in all of this we're going to put this on the back-burner :fire: for now.

**Comment by henare** [comment]
Craig writes:

> I'm of the same view Kat.
> 
> I don't see specific benefits from Lumen over a Google Group.

And Peter writes:

> I have no view one way or the other. Lumen only bobbed up because Tim Hughes included it when I asked if they could assist us. At some stage but probably not this time round it would be great to have a sophisticated online forum for discussion and debate. Given time pressures happy to go with whatever easily obtainable method allows.

**Comment by equivalentideas** [comment]
Awesome to get the perspective of some of the people who'll be using this. Thoughts: I do wonder what platform would be best for the people who aren't in the group yet that we would like to attract? Maybe that doesn't matter and we should just focus on the current users? #my2cents

**Comment by henare** [comment]
I think we're pretty settled on just using the Google Group for now.

@kat I'm assigning this to you so you can add your feedback from the OGP Civil Society Leaders' Workshop or simply close this if your feedback is for us to just use the Google Group :maple_leaf:

**Comment by kat** [comment]
For the time being then we're going with asking current members of the existing google group to affirm and also asking them to confirm 'their commitment to the principles of the network  see https://github.com/AOGPN/opengovernment.org.au/issues/59

**Comment by maxious** [comment]
OKFN uses Discourse and I do get emails just like google groups that you can reply to https://discuss.okfn.org/t/enable-mailing-list-capabilities-of-discourse/219 https://meta.discourse.org/t/new-reply-via-email-support/7764 or even start new threads https://discuss.okfn.org/t/testing-out-starting-a-topic-via-email/1183/3

**Comment by henare** [comment]
@maxious amazing :sparkles: Thanks, I've updated the above :point_up:

**Comment by keithpitty** [comment]
:+1: for Discourse. I find it a delight to use compared to Google Groups. The only negative I see is the need to install it on a server (https://github.com/discourse/discourse/blob/master/docs/INSTALL.md).

**Comment by henare** [comment]
Me on Slack earlier (edited):

> I think @maxious' helpful comment totally sways me to Discourse
> Lumen is hacky, Discourse rocks
> Unless we want to use something like Loomio then I think we should probably just go for it
> We still need a server though and all the overhead that comes with that

**Comment by kat** [comment]
reopening because it hasn't gone away. There's too big a gap between people signing to the network and being able to connect with fellow Network members. Over to you @henare

**Comment by henare** [comment]
Unless we have some esoteric requirements, which I don't think is the case, Discourse seems like the obvious choice for a way for the network to communicate. It now seems like the obvious choice because we know it can do all that Lumen does and more, and nicer.

So our choices are now: no forum (definitely doesn't sound like that's what we want), Discourse (it's the only good choice for a forum), or something esoteric like Loomio for consensus building (maybe that's a separate thing?).

**Comment by kat** [comment]
there's even discussion about  discourse/loomio integration https://github.com/AOGPN/opengovernment.org.au/issues/122

**Comment by henare** [comment]
I'm going to use Ansible to provision the server over here: https://github.com/AOGPN/server

**Comment by henare** [comment]
A basic Discourse server is now live: https://forum.opengovernment.org.au/

We've still got to do the configuration and customisation: https://github.com/AOGPN/server/issues/2
