### ISSUE TITLE
Add a link to this repository

### ISSUE THREAD

**Issue by henare** [AOGPN/opengovernment.org.au#52]
This repository's issues are important. They're not just bugs with the theme code, we've also got content issues and we're also starting to put to dos for the network. So we should add a link somewhere. In the footer? "Report a problem or suggest an idea"?

**Comment by kat** [comment]
good point @henare!

**Comment by kat** [comment]
I've done the dumb thing and added this into the footer - could be better positioned, but it's there.

**Comment by henare** [comment]
:+1: 

There was a formatting issue that meant the link wasn't working, I've fixed this up.
