### ISSUE TITLE
Create pages for the working groups

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#60]
Updated by @henare: After reviewing the OGP Grand Challenges, the OGP themes, the OGP thematic working groups, and what the Network had already discussed, we've come up with these working groups as a starting point for this first action plan:
- Public Services
- Public Resources (Note on page that this includes: Natural resources)
- Access to Information (Note on page that this includes: Open data)
- Civic Participation (Note on page that this includes: Citizen engagement, creating safer communities)
- Anti Corruption

**Comment by henare** [comment]
I've created the basic pages and added them to the menu. Now on to creating starting points, including commitments, which is covered by #62.
