### ISSUE TITLE
Link to the Government site (and wiki?)

### ISSUE THREAD

**Issue by henare** [AOGPN/opengovernment.org.au#61]
I don't think we have links to the Government sites anywhere. Since these have more information on the Government's process, and how to participate in that, I think it's rather important.

**Comment by equivalentideas** [comment]
In the ['about the OGP' section of the about page](https://opengovernment.org.au/about/#section-2), we introduce the Australian Government’s involvement. That seems like a good place to add this (these) link(s) for starters.

**Comment by equivalentideas** [comment]
Gonna this as a starting point.

> The Australian Government committed the country to becoming an OGP member in November 2015. It has set up a [website with resources and announcements](http://ogpau.govspace.gov.au/) relating to Australia’s OGP membership. This includes the [framework and schedule](http://ogpau.govspace.gov.au/national-action-plan/) by which the government will collaborate with civil society to develop our first OGP Action Plan by July 2016.

:snowboarder: jump in and improve to your hearts content here https://opengovernment.org.au/wp-admin/post.php?post=968&action=edit

**Comment by equivalentideas** [comment]
Added and adjusted the text a bit, closing this and if you had another place in the site you wanted to add this link @henare just reopen or add a new issue :+1:

 ![screen shot 2016-01-29 at 4 16 31 pm](https://cloud.githubusercontent.com/assets/1239550/12667770/e1fbb804-c6a3-11e5-84cc-3622e974a80e.png)
