### ISSUE TITLE
Add framework/template to working group pages to provide people a tangible starting point to build on

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#62]
The working group pages should have framework for the people to use/be consistent/get straight into it.

Including:
- design a series of questions for group leaders to answer about the nature of the group and why it exists
- some starting point commitments taken from elsewhere that resonate/seem appropriate and/or actual draft commitments.

**Comment by equivalentideas** [comment]
I've made a Google doc for working on this https://docs.google.com/document/d/1AFaX0cevPgir2uJsBmvmlwMYvAdEzmKJgnecKzUWkbQ/edit

**Comment by kat** [comment]
This is guidance or later a form for a working group leader or someone they assign to communicate the progress of that working group on a given commitment. 
Relevant documents from the OGP are the commitment template in [Action Plan Template Guidance](http://www.opengovpartnership.org/sites/default/files/attachments/Action%20Plan%20Template%20and%20Guidance%202014.pdf) and the new review tool (find link!)

**Comment by kat** [comment]
also [assessing action plan commitments for relevance to OGP values](http://www.opengovpartnership.org/sites/default/files/attachments/OGPvaluesguidancenote.pdf)
One example of a non-relevant commitment from Shreya - "The Government needs to make sure the beaches are clean" That's wonderful thing to aim for but if there is no connection to Openness transparency or participation in that commitment then it's not appropriate for an OGP action plan commitment.

**Comment by henare** [comment]
Don't forget to add a link to the specific topic for the working group on the Google Group on each working group's page.

**Comment by equivalentideas** [comment]
Also a link to join the network and in the template say something like:

> Help kick off this working group by filling out this template and posting your thoughts to the google group.

**Comment by kat** [comment]
For a first dumb thing I've copied and pasted [this text ](https://docs.google.com/document/d/1AFaX0cevPgir2uJsBmvmlwMYvAdEzmKJgnecKzUWkbQ/edit#heading=h.r3siihtsifiq) to all the working group pages.
