### ISSUE TITLE
Add working groups to front page

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#63]
So people can get straight into the action.

**Comment by henare** [comment]
- [x] Get "read more" links working
- [x] Decide what should happen with the "latest posts" and picture sections

**Comment by henare** [comment]
We've decided to remove the "latest posts" and picture sections and just have the intro text the only thing in the box.

Assigning to @equivalentideas to finish off this frontend stuff.

**Comment by equivalentideas** [comment]
> We've decided to remove the "latest posts" and picture sections and just have the intro text the only thing in the box.

I've done that and made the text bigger to pull people in more.

![screen shot 2016-02-02 at 12 01 56 pm](https://cloud.githubusercontent.com/assets/1239550/12736529/1d5b0b6c-c9a5-11e5-8a9e-1be2e0a19979.png)

I think we should make the call to action 'read more' link text more about doing something.

**Comment by equivalentideas** [comment]
At the moment in the admin interface, and in the code, these tabs are still managed as 'countries', rather than 'working groups'. It's a bit of work to adjust that and since there'll only be a small group using the admin interface in the short-term, we've decided to leave that as is.

Closing this as the front-end changes are done.
