### ISSUE TITLE
  Change the UK image to Australia 

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#7]
(via Craig) Change the UK image to Australia including Tassie in banner

**Comment by kat** [comment]
- replacing http://www.opengovernment.org.uk/wp-content/themes/opengov/img/uk_open_gov_logo.png

**Comment by equivalentideas** [comment]
Thanks @kat. This has been done in https://github.com/AOGPN/opengovernment.org.au/issues/1#issuecomment-172439499
