### ISSUE TITLE
Change to UK to Aus name in site banner

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#8]
(via Craig) Change the name to: AU OPEN GOVERNMENT PARTNERSHIP NETWORK

**Comment by kat** [comment]
Let's use full words and make that Australian rather than AU (even if it invokes the tennis even more than usual)

**Comment by equivalentideas** [comment]
:+1: Closed by https://github.com/AOGPN/opengovernment.org.au/issues/1#issuecomment-172439499

![screen shot 2016-01-18 at 5 32 51 pm](https://cloud.githubusercontent.com/assets/1239550/12384771/cccd9436-be09-11e5-99a2-e9171885aaf0.png)
