### ISSUE TITLE
embed a demo google group

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#84]
We need to see what having the forum on the website looks like and if we can embed them by working group under each working group

We don't currently have permission to add the group Craig made nor is it resolved if this is the right group to use. see #83

**Comment by craigthomler** [comment]
Hi Kat,

You have my permission to add it, so you can test this out.

Just register and I'll make you an admin.

Google has some advise on how to embed it into a site that might be useful:
https://support.google.com/groups/answer/1191206?hl=en

Cheers,

Craig

---

Craig Thomler

http://egovau.blogspot.com
http://twitter.com/CraigThomler
http://au.linkedin.com/in/craigthomler
http://www.slideshare.net/CraigThomler
http://www.slideshare.net/CraigThomler%20

_Mobile:_ 0411 780 194 (_International:_ +61 411 780 194)
_Phone:_ 02 6161 4508 (_International: *+61 2 6161 4508)
*Skype:_ craig.thomler

**Comment by kat** [comment]
Hi @craigthomler , I've already joined - I think I need to be an admin. Thanks, I've seen the embedding help :-)

**Comment by kat** [comment]
closing this as we no longer need a demo group

**Comment by craigthomler** [comment]
Cool, I've promoted you to Owner. (equivalent of Admin)

Cheers,

Craig

---

Craig Thomler

http://egovau.blogspot.com
http://twitter.com/CraigThomler
http://au.linkedin.com/in/craigthomler
http://www.slideshare.net/CraigThomler
http://www.slideshare.net/CraigThomler%20

_Mobile:_ 0411 780 194 (_International:_ +61 411 780 194)
_Phone:_ 02 6161 4508 (_International: *+61 2 6161 4508)
*Skype:_ craig.thomler

**Comment by kat** [comment]
awesome Craig thanks!

kat@oaf.org.au
Founder, Director, Worker OpenAustralia Foundation
http://openaustraliafoundation.org.au/
openaustralia http://openaustralia.org/ | planningalerts
http://planningalerts.org.au/| electionleaflets
http://electionleaflets.org.au/ | righttoknow http://righttoknow.org.au/
| theyvoteforyou http://theyvoteforyou.org.au/
