### ISSUE TITLE
give new users a sense of what's going on in their area of interest

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#85]
by embedding google group thread to the relevant working groups

**Comment by kat** [comment]
we're not sure if this is possible

**Comment by equivalentideas** [comment]
> we're not sure if this is possible

Turned out that it wasn't possible.

I'm gonna close this issue. If someone wants to reopen it would be good to rephrase it around what the problem/opportunity is from the users perspective. Or open a new issue :)
