### ISSUE TITLE
Add a link to the membership form

### ISSUE THREAD

**Issue by henare** [AOGPN/opengovernment.org.au#86]
https://opengovernment.org.au/get-involved/

**Comment by kat** [comment]
this is part if the other form we already made for #76

**Comment by henare** [comment]
@kat is this form also supposed to ask people to become a network member?

For the moment we're going to reuse the form we already had from #76 and add back the option to also become a member. That way people can still provide their details and optionally choose to be a network member.

**Comment by equivalentideas** [comment]
The introduction to the form is currently:

> ## Join the Australian Open Government Partnership Civil Society Network
> 
> We are a network of individuals and organisations committed to helping governments work better by promoting transparency, open government, public participation, deliberation and accountability. Formed following the Australian Government’s decision to join the Open Government Partnership, we support this goal through information-sharing and working cooperatively to help government set and meet ambitious and achievable open government reforms.

This should change:
- to reflect that you can optionally not become a member, **the chief focus of the form is to introduce yourself to the network so it can help direct your contributions and work with you**
- to give people some indication of why they're handing over there information and what we'll do with it.

**Comment by kat** [comment]
I Think the form is to allow people to join the network, to do that we ask people to

1) agree to basic terms - that they're acting in civil society interests and don't have conflicts 
and
2) provide their information as per the form on the UK site

Are we on the same page?

**Comment by henare** [comment]
@kat so people shouldn't be able to submit the form if you're not applying for membership?

**Comment by kat** [comment]
I think we agreed that by agreeing to the terms and providing your info you become a member. The group will accept you on face value.

**Comment by kat** [comment]
So there's no wait - you get in straight away.

**Comment by equivalentideas** [comment]
Ok cool :+1: we'll take the form back to not having an option not to become a member. You fill in details, then read the terms, agree by submitting and then get directed to start working.

**Comment by kat** [comment]
Nice!

kat@oaf.org.au
Founder, Director, Worker OpenAustralia Foundation
http://openaustraliafoundation.org.au/
openaustralia http://openaustralia.org/ | planningalerts
http://planningalerts.org.au/| electionleaflets
http://electionleaflets.org.au/ | righttoknow http://righttoknow.org.au/
| theyvoteforyou http://theyvoteforyou.org.au/

**Comment by henare** [comment]
We're done!
