### ISSUE TITLE
make it easy for working group facilitators to add first round of info about their group

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#90]
Make a google doc for each group with the questions and link to it from the working group page

**Comment by kat** [comment]
I've created a first version of this to model for the rest  https://opengovernment.org.au/working-groups/access-to-information/ but it seems clunky @henare @equivalentideas please review.

**Comment by equivalentideas** [comment]
I'll have a look now

**Comment by equivalentideas** [comment]
I think it is a bit of a complex process at the moment. Could we simplify it by taking the questions off the current page and having a big button to go to the google doc. Then it's clear that all the editing happens in here?

![screen shot 2016-02-03 at 12 29 31 pm](https://cloud.githubusercontent.com/assets/1239550/12770118/d15be326-ca71-11e5-8eb5-337faf23e9d4.png)

What do ya think @kat ?

**Comment by kat** [comment]
Yes good I was thinking that too :+1: how about changing kick things off to something plainer like 'begin by' and then say what will happen next 'we'll work with you to put that information here' or similar

**Comment by kat** [comment]
links for the questions for each working group [access to information](https://docs.google.com/document/d/1IXiY3oCJi5WpqUK_sIn6a2dmPmqIre7LzbtsrvUTMKg/edit#), [anti corruption](https://docs.google.com/document/d/1Y4CdGWdO27r49nKI9K2ZqTk_VdjyNjq-7l85MW2T9hE/edit), [civic participation](https://docs.google.com/document/d/1Y4CdGWdO27r49nKI9K2ZqTk_VdjyNjq-7l85MW2T9hE/edit), [public resources](https://docs.google.com/document/d/1n9l-pk0ydsJvemLtZQlMG2VKYqG-VemnaFDHF-LGBvo/edit#heading=h.5h1ae5tiuumv), and [public services](https://docs.google.com/document/d/1czwdaIzqyC9k24jAb7mt3eSDWyRiK3dNp7xrik_GWjE/edit#heading=h.5h1ae5tiuumv). Please can you @equivalentideas proliferate?

**Comment by equivalentideas** [comment]
@kat Yep I'll set this up for all the pages now.
- [x] change the text and add links to all the pages
  - [x] Access to information
  - [x] Anti corruption
  - [x] civic participation
  - [x] public resources
  - [x] public services
- [x] add the button style to the css as something like .btn-secondary

**Comment by equivalentideas** [comment]
@kat I think you need to change the permissions on those docs so anyone can edit/view with the link. I can't access them at the moment.

**Comment by equivalentideas** [comment]
I've implemented this across the pages. [I used a light teal colour](https://github.com/AOGPN/opengovernment.org.au/commit/840006b9cbe81010b7f7dab62c51937b3b5a1655) that's used for the tabs interface on the front page for the button colour, rather than the green. I didn't wanted to use an existing colour pattern from the site for familiarity. It could be a bit light with the white text? Let me know what ya think.

![screen shot 2016-02-03 at 3 21 39 pm](https://cloud.githubusercontent.com/assets/1239550/12772867/e746dc14-ca89-11e5-834e-e23e96d59325.png)

Before we close this we need to check that all the links are correct:

> @kat I think you need to change the permissions on those docs so anyone can edit/view with the link. I can't access them at the moment.

**Comment by equivalentideas** [comment]
Hmm, I think that light teal is too weak. I think using the same primary orange will do the job.

**Comment by equivalentideas** [comment]
Made that change

**Comment by equivalentideas** [comment]
I can see you're opening the docs now @kat :+1: I'm checking that I got the links right. Found one a messed up already.

**Comment by equivalentideas** [comment]
@kat the link for the civic participation doc above is the same one of anti corruption, could you drop that in here again.

**Comment by equivalentideas** [comment]
Fixed up another of the links I copied wrong to the one provided above. The last thing on this issue is to make sure all the links work.

**Comment by kat** [comment]
civic participation is fixed - checking links

**Comment by equivalentideas** [comment]
From chat:

> What's wrong with the phrase "This page needs" ... and how would you improve it @equivalentideas?

hmmm.

It's a bit long and not quite as clear as it could be. @kat What about:

> This page needs some clear information about the working group added. This will to help members contribute to draft National Action Plan commitments.

**Comment by equivalentideas** [comment]
@kat the Google Doc link on Civic Participation still points to Anti Corruption https://opengovernment.org.au/working-groups/civic-participation/

**Comment by kat** [comment]
@equivalentideas sorry got interrupted. With the This site needs I thought that actual bit of the sentence passive. How about Giving a direct instruction. Use **Add clear information *\* instead of **This site needs**

**Comment by kat** [comment]
checking links now - again...

**Comment by kat** [comment]
links fixed - just that one wording

**Comment by equivalentideas** [comment]
>  How about Giving a direct instruction. 

How about:

> You can get this page started by adding some basic information about the working group. This will ...

or:

> Add some basic information about the working group. ...

**Comment by kat** [comment]
You're trying to make it gentler and less stark? Is there another way to do that? "You can" isn't direct and "get" is an icky word.

**Comment by kat** [comment]
if nothing comes to mind, then let's use You can for now - it's an improvement over This page needs .... :+1:

**Comment by kat** [comment]
or leave it for now even.
