### ISSUE TITLE
Link to timeline in welcome blogpost

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#98]
It's not clear what the four weeks is referred to in this welcome post https://opengovernment.org.au/2016/02/02/welcome/ let people know where this fits into the process - why it's important

**Comment by equivalentideas** [comment]
I added it as a link to the first time it sats 'under four weeks'. Do you think a more explicit link would be better? Something like:

> ... just under four weeks ([see the Government’s timeline](http://ogpau.govspace.gov.au/national-action-plan/#Stage_2_Drafting_and_Live_Event)) ...

**Comment by kat** [comment]
that's good to begin - replace with link to #47 on this site when available.

**Comment by equivalentideas** [comment]
> that's good to begin - replace with link to #47 on this site when available.

I've noted that on that issue so I'll close this one.
